module.exports = [
    {
        imagen: "/images/nike-hombre/blazer-low-jumbo-77/1.png" ,
        producto: "Nike Blazer Low Jumbo '77" ,
        categoria: "Hombre" ,
        imagen2: "/images/nike-hombre/blazer-low-jumbo-77/2.png" ,
        imagen3: "/images/nike-hombre/blazer-low-jumbo-77/3.png" ,
        imagen4: "/images/nike-hombre/blazer-low-jumbo-77/4.png" ,
        precio: "99,99" ,
        precioOferta: "59,97" ,
        tallas: [40, 41, 42, 43, 46, 48, 52] ,
        descripcion: "Dicen que no vale la pena cambiar lo que ya funciona, y por nosotros bien. Las superestrellas clásicas del estilo urbano se renuevan en las Nike Blazer Low '77 Jumbo. Ofrecen el look clásico que más te gusta con un diseño Swoosh oversize y unos cordones enormes. Su lengüeta de espuma suave y las costuras más gruesas destacan el look icónico alabado por el estilo urbano desde el 77."
    } ,
    {
        imagen: "/images/nike-hombre/wearallday/1.png" ,
        producto: "Nike Wearallday" ,
        categoria: "Hombre" ,
        imagen2: "/images/nike-hombre/wearallday/2.png" ,
        imagen3: "/images/nike-hombre/wearallday/3.png" ,
        imagen4: "/images/nike-hombre/wearallday/4.png" ,
        precio: "69,99" ,
        precioOferta: "41,97" ,
        tallas: [39, 42.5, 44, 45, 46.5, 47] ,
        descripcion: "¿Qué se sentiría al llevar un par de nubes atadas a los pies? No podemos saberlo, pero creemos que Nike Wearallday están bastante cerca. Con un acolchado suave alrededor del tobillo, una lengüeta gruesa y acolchada, y una espuma increíblemente suave en la planta del pie, estas zapatillas de inspiración deportiva son la encarnación de la comodidad. La malla de la parte superior aporta una transpirabilidad duradera y la suela exterior de goma con diseño tipo gofre proporciona tracción durante todo el día"
    },
    {
        imagen: "/images/nike-hombre/pegasus-turbo-next-nature/1.png" ,
        producto: "Nike Pegasus Turbo Next Nature" ,
        categoria: "Hombre" ,
        imagen2: "/images/nike-hombre/pegasus-turbo-next-nature/2.png" ,
        imagen3: "/images/nike-hombre/pegasus-turbo-next-nature/3.png" ,
        imagen4: "/images/nike-hombre/pegasus-turbo-next-nature/4.png" ,
        precio: "" ,
        precioOferta: "159,99" ,
        tallas: [39, 40, 42, 43, 44, 46, 47] ,
        descripcion: "Deja que este Pegaso te impulse durante los momentos más complicados de la carrera. Con una espuma reciclada, más ligera y reactiva y una parte superior de plumas, este modelo está confeccionado para aumentar el ritmo sin sacrificar la comodidad mientras alcanzas tu mejor marca personal. Este modelo inmortal está confeccionado de manera responsable con, al menos, un 50 % de material reciclado por peso, para mantener su filosofía de eficacia demostrada para el día a día"
    },
    {
        imagen: "/images/nike-hombre/blazer-mid-jumbo-77/1.png" ,
        producto: "Nike Blazer Mid Jumbo '77" ,
        categoria: "Hombre" ,
        imagen2: "/images/nike-hombre/blazer-mid-jumbo-77/2.png" ,
        imagen3: "/images/nike-hombre/blazer-mid-jumbo-77/3.png" ,
        imagen4: "/images/nike-hombre/blazer-mid-jumbo-77/4.png" ,
        precio: "109,99" ,
        precioOferta: "65,97" ,
        tallas: [36, 38.5, 40, 41, 42, 44, 47] ,
        descripcion: "Alabadas por muchos por su aspecto y su sensación de resistencia, el básico de armario se actualiza con las Nike Blazer Mid ' 77 Jumbo.Aprovecha el look clásico que más te gusta, que ahora cuenta con un talón elástico con textura de pana y unas presillas grandes para que puedas ponértelas y quitártelas fácilmente.El diseño Swoosh extragrande y los cordones enormes añaden un toque divertido"
    }, 
    {
        imagen: "/images/nike-hombre/air-max-systm/1.png" ,
        producto: "Nike Air Max SYSTM" ,
        categoria: "Hombre" ,
        imagen2: "/images/nike-hombre/air-max-systm/2.png" ,
        imagen3: "/images/nike-hombre/air-max-systm/3.png" ,
        imagen4: "/images/nike-hombre/air-max-systm/4.png" ,
        precio: "99,99" ,
        precioOferta: "59,97" ,
        tallas: [39, 40, 42, 43, 45, 46] ,
        descripcion: "Los looks Max, con sensación Max. Las Air Max SYSTM recuperan todo lo que te gustan de tu rollo favorito de los 80 (sin el pantalón de paracaídas). La amortiguación Nike Air probada y visible se combina con una parte superior elegante inspirada en el deporte. Air Max cumple de nuevo"
    },
    {
        imagen: "/images/nike-hombre/air-huarache/1.png" ,
        producto: "Nike Air Huarache" ,
        categoria: "Hombre" ,
        imagen2: "/images/nike-hombre/air-huarache/2.png" ,
        imagen3: "/images/nike-hombre/air-huarache/3.png" ,
        imagen4: "/images/nike-hombre/air-huarache/4.png" ,
        precio: "129,99" ,
        precioOferta: "77,97" ,
        tallas: [38, 40, 42.5, 43, 44, 45, 47] ,
        descripcion: "Diseñadas para adaptarse a los pies y ofrecer mayor comodidad, las Nike Air Huarache recuperan un modelo urbano favorito. Los toques de piel suave de la parte superior se combinan con un tejido de neopreno supertranspirable y con un brillo perfecto para ofrecer un estilo sencillo. La zona del tobillo de corte bajo y la confección tipo botín mantienen la elegancia. El icónico clip del talón y el logotipo aislado ofrecen el look de principios de los 90 que más te gusta"
    },
    {
        imagen: "/images/nike-hombre/air-more-uptempo-96/1" ,
        producto: "Nike Air More Uptempo '96" ,
        categoria: "Hombre" ,
        imagen2: "/images/nike-hombre/air-more-uptempo-96/2" ,
        imagen3: "/images/nike-hombre/air-more-uptempo-96/3" ,
        imagen4: "/images/nike-hombre/air-more-uptempo-96/4" ,
        precio: "179,99" ,
        precioOferta: "107,97" ,
        tallas: [42.5, 43, 45, 46, 48] ,
        descripcion: "El diseño atrevido y llamativo es exclusivo del estilo A-I-R. Con un diseño inspirado en el baloncesto de altos vuelos y el arte del grafiti de los 90, estas zapatillas son el centro de atención. Además, las unidades Max Air del talón, el antepié y el mediopié proporcionan una amortiguación cómoda para que tu aspecto esté a la par de tu comodidad"
    },
    {
        imagen: "/images/air-force-retro.png" ,
        producto: "Nike Air Forcr 1 Low Retro" ,
        categoria: "Hombre" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "149,99" ,
        precioOferta: "119,97" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "/images/react-miler.png" ,
        producto: "Nike React Miler 3" ,
        categoria: "Hombre" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "129,99" ,
        precioOferta: "77,97" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "/images/nike-tech.png" ,
        producto: "Nike Sportswear Tech Fleece" ,
        categoria: "Hombre" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "119,99" ,
        precioOferta: "71,97" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "/images/blazer-plataform.png" ,
        producto: "Nike Blazer Low Platform" ,
        categoria: "Hombre" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "99,99" ,
        precioOferta: "59,97" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "/images/pegasus-trail-4.png" ,
        producto: "Nike Pegasus Trail 4" ,
        categoria: "Mujer" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "" ,
        precioOferta: "" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "" ,
        producto: "" ,
        categoria: "Mujer" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "" ,
        precioOferta: "" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "" ,
        producto: "" ,
        categoria: "Mujer" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "" ,
        precioOferta: "" ,
        tallas: "" ,
        descripcion: ""
    },{
        imagen: "" ,
        producto: "" ,
        categoria: "Mujer" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "" ,
        precioOferta: "" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "" ,
        producto: "" ,
        categoria: "Mujer" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "" ,
        precioOferta: "" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "" ,
        producto: "" ,
        categoria: "Mujer" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "" ,
        precioOferta: "" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "" ,
        producto: "" ,
        categoria: "Mujer" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "" ,
        precioOferta: "" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "" ,
        producto: "" ,
        categoria: "Mujer" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "" ,
        precioOferta: "" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "" ,
        producto: "" ,
        categoria: "Mujer" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "" ,
        precioOferta: "" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "" ,
        producto: "" ,
        categoria: "Mujer" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "" ,
        precioOferta: "" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "" ,
        producto: "" ,
        categoria: "Mujer" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "" ,
        precioOferta: "" ,
        tallas: "" ,
        descripcion: ""
    },
    {
        imagen: "" ,
        producto: "" ,
        categoria: "Mujer" ,
        imagen2: "" ,
        imagen3: "" ,
        imagen4: "" ,
        precio: "" ,
        precioOferta: "" ,
        tallas: "" ,
        descripcion: ""
    }
]